[global]
# Production settings for resume customizer
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Ultra-fast server settings for maximum performance
runOnSave = false
allowRunOnSave = false
port = 5000
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50  # Reduced for speed
maxMessageSize = 50  # Reduced for speed
baseUrlPath = ""
enableWebsocketCompression = true
enableStaticServing = false
headless = true
fileWatcherType = "none"  # Disable file watching for speed

[browser]
# Browser settings optimized for performance
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Professional theme for resume customizer
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Ultra-fast performance optimizations
magicEnabled = false  # Disable magic for speed
fastReruns = true
enforceSerializableSessionState = false
# installTracer removed - not a valid option

[client]
# Client-side optimizations
showErrorDetails = true
toolbarMode = "auto"

[logger]
# Logging for monitoring
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d [%(levelname)s] %(name)s: %(message)s"
